name: wiki_places
description: WikiPlaces app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.1
  firebase_core: ^1.8.0
  firebase_analytics: ^8.3.4
  firebase_performance: ^0.8.0+4
  firebase_crashlytics: ^2.6.2
  sentry_flutter: ^6.4.0
  cross_connectivity: any
  cupertino_icons: ^1.0.2
  sorted_list: ^1.0.0
  geolocator: ^8.2.0
  webview_flutter: ^3.0.2
  google_maps_flutter: ^2.0.1
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
